### ISSUE TITLE
SSL error: "SSL23_GET_SERVER_HELLO:unknown protocol"

### ISSUE THREAD

**Issue by xiconet** [juanriaza/python-mega#7]
Hello,
I get the following error when trying to login to mega, on a machine running WinXP-sp3, python 2.7:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\mega\mega.py", line 31, in login
    self._login_user(email, password)
  File "C:\Python27\lib\site-packages\mega\mega.py", line 39, in _login_user
    resp = self._api_request({'a': 'us', 'user': email, 'uh': uh})
  File "C:\Python27\lib\site-packages\mega\mega.py", line 110, in _api_request
    timeout=self.timeout)
  File "C:\Python27\lib\site-packages\requests\api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 382, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

I gave a try to the `requests_toolbelt SSLadapter`, using something like:

```
from requests_toolbelt import SSLAdapter
s = requests.Session()
s.mount('https://', SSLAdapter(ssl.PROTOCOL_SSLv3))
s.post(url, params=params, data=data)
```

this time I got this message:

```
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

Any idea of what's happening here and how to work around this issue?
Thanks in advance for your help

**Comment by Matt3o12** [comment]
This project has not been worked on for over 2 years and back then, the project was buggy and didn't work well.  

Unless you want to fix it yourself, I suggest you checkout https://github.com/richardasaurus/mega.py (which seems to be way more active).

**Comment by xiconet** [comment]
Hello.
Thanks for the reply. In fact my issue seems to be specific to the python version I was using, maybe its ssl library, rather than to a bug in your code. I finally managed to put your program at work with python 3.3, with some minor modifications. The `mega.py` code is almost identical, and here again it can be made to work with Py33 but not with Py27, at least in my hands. After some investigation it appears that my issue could be due to the fact that mega.co uses some specific ssl cipher which is not handled "out of the box" by python27. At least that's my current understanding but I'm not very informed on these matters. Maybe some ssl wrapper would do the trick, but I've yet to find how to do this. 
Anyway thanks for your code, which has proven very useful since the "official" doc is more than minimal. Cryptography/encryption is not an easy matter, at least for me.
Joyeux Noel!

**Comment by stefanocudini** [comment]
this issue is closed but is not solved :-(
